### PR TITLE
Update image

### PR DESCRIPTION
**Pull request by bryan-brancotte**
Ability to update component regarding their cloud identifier and inheriting parent.
I let aside the authorization for futur work.

### CODE REVIEW

**Comment by bryan-brancotte** [comment]
Hi,
We use it on our fork, could you merge it ?

**Comment by loomis** [comment]
@schaubl Can you review this when you have a chance?

**Comment by 0xbase12** [comment]
@bryan-brancotte I can add this function to the api master branch like in my last comment and reference your pull request in the comment of the commit.

If you are okey with this, tell me and if not, waiting on a compatible version with our api :)

**Comment by bryan-brancotte** [comment]
No problem !

**Comment by 0xbase12** [comment]
Added into master: https://github.com/slipstream/SlipStreamPythonAPI/commit/1ef47a9c286bc3bce7a036ab12e6b001a6f74e5f

**Pull request closed without merging**
