### PR TITLE
Authentication only when needed

### PR DESCRIPTION
**Pull request by bryan-brancotte**

### CODE REVIEW

**Comment by bryan-brancotte** [comment]
Is the equivalent is already done thanks to cimi_login ?

**Comment by 0xbase12** [comment]
@bryan-brancotte if you mean the cookie session expiry management, yes it has been done by adding an option reauthenticate when your create Api instance.
Check following commit: 0b9c52ecbd908f9d36712907952b01bda1c8c737

**Comment by bryan-brancotte** [comment]
Thanks for your reply, the parameter force to re auth every time ? Or just
when needed ?
Best regards

**Comment by 0xbase12** [comment]
Only when needed.

**Comment by 0xbase12** [comment]
I think everything in this PR is already in master or in another pending pull request.

@bryan-brancotte  Could I close this pull request?

**Comment by bryan-brancotte** [comment]
Yes it can be closed

**Pull request closed without merging**
